# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
  
    config.vm.define "host1"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    
    config.vm.provision :ansible do |ansible|
      ansible.playbook = "../ansible/app_install.yml"
      ansible.groups = {
        "docker_group" => ["host1"]
      }
    end
  end