  
---
- hosts: all
  vars:
    username: ubuntu
    docker_hub_app_tag: latest

  roles:
    - role: docker_install
      become: true
      vars:
        docker_users:
          - "{{ username }}"
    - role: application_install
      python_app_tag: "{{ docker_hub_app_tag }}"