
---
- include: install_docker.yml

- name: Copy and run docker compose
  hosts: docker_group
  become: yes
  tasks:
    - name: Create directory in /opt
      file:
        path: /opt/python_app
        state: directory

    - name: Copy docker-compose.yml
      copy:
        src: ../python_app/docker-compose.yml
        dest: /opt/python_app

    - name: Run docker-compose
      community.docker.docker_compose: 
        project_src: /opt/python_app
        files:
            - docker-compose.yml
        state: present